---
title: "PFAS Data Exploration"
author: "Erin Franke"
date: "2023-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
library(readxl)
library(sf)
```

```{r, message=FALSE, warning=FALSE}
pfas <- read_xlsx("../data/Twin Cities PFAS Data Ticket WO00000021224685.xlsx", sheet=2)
```

General statistics from the data

```{r}
skim(pfas)
```

Top 7 types of PFAS with percent detection and total number of samples.

```{r}
pfas %>%
  count(CHEMICAL_NAME, DETECT_FLAG) %>%
  pivot_wider(names_from = DETECT_FLAG, values_from = n) %>%
  mutate(percent_detect = Y/(Y+N), total = N+Y) %>%
  arrange(desc(percent_detect)) %>%
  filter(total > 5000) %>%
  mutate(commonName = c("PFBA", "PFOA", "PFPeA", "PFHxA", "PFOS", "PFHxS", "PFBS"))
```

## Understanding contamination based on sample type (well, stream, etc)

```{r}
pfas7 <- pfas %>%
  filter(CHEMICAL_NAME %in% c("Perfluorobutanoic acid", "Perfluorooctanoic acid", "Perfluoropentanoic acid", "Perfluorohexanoic acid", "Perfluorooctane sulfonate", "Perfluorohexane sulfonate", "Perfluorobutane sulfonate")) %>%
  mutate(commonName = case_when(CHEMICAL_NAME == "Perfluorobutanoic acid" ~ "PFBA", 
                                CHEMICAL_NAME == "Perfluorooctanoic acid" ~ "PFOA", 
                                CHEMICAL_NAME == "Perfluoropentanoic acid" ~ "PFPeA",
                                CHEMICAL_NAME == "Perfluorohexanoic acid" ~ "PFHxA", 
                                CHEMICAL_NAME == "Perfluorooctane sulfonate" ~ "PFOS", 
                                CHEMICAL_NAME == "Perfluorohexane sulfonate" ~ "PFHxS", 
                                CHEMICAL_NAME == "Perfluorobutane sulfonate" ~ "PFBS")) %>%
  mutate(LOC_TYPE_2 = case_when(LOC_TYPE_2 == "Well-DOmestic" ~ "Well-Domestic", 
                                TRUE ~ LOC_TYPE_2))
```

We likely want to focus locations that are "Well-Domestic", "Well-Monitoring", and "River/Stream" with "River/Stream Peren".

```{r}
pfas7 %>%
  count(LOC_TYPE_2) %>%
  arrange(desc(n))
```

```{r}
pfas7 %>%
  select(`FACILITY CODE`:CHEMICAL_NAME, `SAMPLE TYPE`, `RESULT NUMERIC`, `LATITUDE`, `LONGITUDE`) %>%
  pivot_wider(names_from = commonName, )
```

