---
title: "PFAS data"
author: "Vivian Powell"
date: "2023-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(skimr)
library(tidyverse)
library(readr)
library(readxl)
library(sf)
library(USAboundaries)
```

Import Data

```{r, warning=FALSE}
pfas <- read_xlsx("../data/Twin Cities PFAS Data Ticket WO00000021224685.xlsx", sheet = 2)
```


Overall Summary

```{r}
skim(pfas)
```

Look at Data

```{r}
head(pfas)
```

Find 7 main PFAs

```{r}
pfas %>%
  count(CHEMICAL_NAME, DETECT_FLAG) %>%
  pivot_wider(names_from = DETECT_FLAG, values_from = n) %>%
  mutate(percent_detect = Y/(Y+N), total = N+Y) %>%
  arrange(desc(percent_detect)) %>%
  filter(total > 5000) %>%
  mutate(commonName = c("PFBA", "PFOA", "PFPeA", "PFHxA", "PFOS", "PFHxS", "PFBS"))
```
PFBA (#1) Exploration
```{r}
pfba <- pfas %>%
  filter(CHEMICAL_NAME == "Perfluorobutanoic acid")

pfba %>% 
  count(`LOC_TYPE_2`) %>%
  arrange(desc(n))

pfba %>%
  group_by(LOC_TYPE_2) %>%
  mutate(count = n()) %>%
  filter(count > 900) %>%
  count(DETECT_FLAG)
```
Counties map

```{r}
mn_counties <- us_counties(resolution = "high", states = c("Minnesota")) %>%
  st_transform(crs = 4269)

st_crs(mn_counties)
```

```{r}
pfas_sf <- pfas %>%
#  filter(LOC_TYPE_2 == "Well-Domestic") %>%
  filter(!is.na(LATITUDE), !is.na(LONGITUDE)) %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"),
                  crs = 4269)

st_crs(pfas_sf)


names_counties <- names(mn_counties) 
names(mn_counties)[names_counties == 'state_name'] <- c("state_name1", "state_name2")

ggplot() +
  geom_sf(data = mn_counties %>% filter(name %in% c("Anoka", "Hennepin", "Ramsey", "Dakota", "Carver", "Washington", "Scott"))) +
  geom_sf(data = pfas_sf %>% filter) 


pfba_sf %>%
  count(`FACILITY TYPE`)

pfas %>%
  count(`FACILITY TYPE`)
```

Temporal Analysis

```{r}
pfas %>%
  group_by(`SYS LOC CODE`, LATITUDE) %>%
  summarize()

ggplot(data = pfas_sf, aes(x = `SAMPLE DATE`)) +
  geom_density()

wells = c("Well",	"Well-Domestic","Well-Monitoring", "Well-Observation", "Well-Other","Well-PubWtrSub")

pfas <- pfas %>%
  mutate(date_post_2015 = (lubridate::year(`SAMPLE DATE`) %in% c("2016","2017", "2018", "2019", "2020", "2021","2022", "2023")), date_pre_2015 = (lubridate::year(`SAMPLE DATE`) %in% c("2010", "2011", "2012","2013", "2014", "2015")))

pfas_temporal_stations <- pfas %>%
  filter(LOC_TYPE_2 %in% wells ) %>%
  group_by(`SYS LOC CODE`) %>%
  summarize(n_recent = sum(date_post_2015), n_early = sum(date_pre_2015)) %>%
  filter(n_recent >=1, n_early >= 1) %>%
  select(`SYS LOC CODE`)

pfas_compare <- pfas %>%
  filter(LOC_TYPE_2 %in% wells ) %>%
  semi_join(pfas_temporal_stations, by = join_by(`SYS LOC CODE`)) %>%
  filter(lubridate::year(`SAMPLE DATE`) %in% c("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")) %>%
  mutate(date_post_2016 = (lubridate::year(`SAMPLE DATE`) %in% c("2016","2017", "2018", "2019", "2020", "2021","2022", "2023")))

pfas_compare %>%
  group_by(`SYS LOC CODE`, date_post_2015) %>%
  summarize()
 
pfba_compare_yes <- pfba_compare %>%  
  group_by(`SYS LOC CODE`, date_post_2015, DETECT_FLAG) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = DETECT_FLAG, values_from = n, values_fill = 0) %>%
  mutate(percent_yes = Y/(Y+N))
  
ggplot(pfba_compare_yes, aes(x = percent_yes, fill = date_post_2015)) + 
  geom_density(alpha = 0.6)

pfas %>%
  ggplot(aes(x = `SAMPLE DATE`)) +
  geom_histogram()
```

```{r}
pfba_latlongs <- pfba_compare %>%
  group_by(`SYS LOC CODE`, LATITUDE, LONGITUDE) %>%
  summarize() %>%
  group_by(`SYS LOC CODE`) %>%
  slice_head()
```

```{r}
pfba_detected_temporal <- pfba_compare_yes %>%
  left_join(pfba_latlongs, by = join_by(`SYS LOC CODE`))
```

```{r}
pfba_detected_pre2015 <- pfba_detected_temporal %>%
  filter(date_post_2015 == FALSE) %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"),
                  crs = 4269)

pfba_detected_post2015 <- pfba_detected_temporal %>%
  filter(date_post_2015 == TRUE) %>% 
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"),
                  crs = 4269)
```

```{r}
ggplot() +
  geom_sf(data = mn_counties %>% filter(name %in% c("Washington"))) +
  geom_sf(data = pfba_detected_pre2015, aes(color = percent_yes), alpha = 0.7) 

ggplot() +
  geom_sf(data = mn_counties %>% filter(name %in% c("Washington"))) +
  geom_sf(data = pfba_detected_post2015, aes(color = percent_yes), alpha = 0.7) 
```
```{r}
pfas %>%
  filter(CHEMICAL_NAME == "Perfluorobutanoic acid", LOC_TYPE_2 %in% wells) %>%
  group_by(lubridate::year(`SAMPLE DATE`), `SYS LOC CODE`) %>%
  count()
```
```{r}
pfas_latlongs <- pfas %>% 
  filter(CHEMICAL_NAME %in% c("Perfluorobutanoic acid", "Perfluorooctanoic acid", "Perfluoropentanoic acid", "Perfluorohexanoic acid", "Perfluorooctane sulfonate", "Perfluorohexane sulfonate", "Perfluorobutane sulfonate"), LATITUDE != "NA", LONGITUDE != "NA") %>%
  group_by(`SYS LOC CODE`, LATITUDE, LONGITUDE) %>%
  summarize() %>%
  group_by(`SYS LOC CODE`) %>%
  slice_head()
```


```{r}
pfas <- pfas%>% 
  filter(CHEMICAL_NAME %in% c("Perfluorobutanoic acid", "Perfluorooctanoic acid", "Perfluoropentanoic acid", "Perfluorohexanoic acid", "Perfluorooctane sulfonate", "Perfluorohexane sulfonate", "Perfluorobutane sulfonate")) %>%
  mutate(commonName = case_when(CHEMICAL_NAME == "Perfluorobutanoic acid" ~ "PFBA", 
                                CHEMICAL_NAME == "Perfluorooctanoic acid" ~ "PFOA", 
                                CHEMICAL_NAME == "Perfluoropentanoic acid" ~ "PFPeA",
                                CHEMICAL_NAME == "Perfluorohexanoic acid" ~ "PFHxA", 
                                CHEMICAL_NAME == "Perfluorooctane sulfonate" ~ "PFOS", 
                                CHEMICAL_NAME == "Perfluorohexane sulfonate" ~ "PFHxS", 
                                CHEMICAL_NAME == "Perfluorobutane sulfonate" ~ "PFBS")) %>%
  mutate(LOC_TYPE_2 = case_when(LOC_TYPE_2 == "Well-DOmestic" ~ "Well-Domestic", 
                                TRUE ~ LOC_TYPE_2)) 


pfas_superfund <- pfas %>%
  filter(`FACILITY TYPE` == "Superfund", LOC_TYPE_2 %in% wells) %>%
  #filter(COUNTY == "Washington") %>%
  mutate(detected = ifelse(DETECT_FLAG == "Y", TRUE, FALSE), year = year(`SAMPLE DATE`)) %>%
  group_by(year, commonName, `SYS LOC CODE`) %>%
  summarize(facility = unique(`FACILITY NAME`), facility_code = unique(`FACILITY CODE`), perc_detected = sum(detected)/n()) %>%
  left_join(pfas_latlongs, by = join_by(`SYS LOC CODE`)) %>%
  rename(sys_loc_code =`SYS LOC CODE`)

write.csv(pfas_superfund, "C:\\Users\\vivianpowell\\Desktop\\STAT 456\\project\\vivian-erin-456\\pfas_superfund.csv")
```
